### ISSUE TITLE
Criar botão "Aplicar Modelo p/ todas as Máquinas"

### ISSUE THREAD

**Issue by PauloImmig** [PauloImmig/MachineMonitoring#10]
Criar botão "Aplicar Modelo p/ todas as Máquinas", para o caso de todas serem utilizadas com um mesmo modelo (é a situação mais comum);

**Comment by tecsistel** [comment]
Prioridade 1:
1. Criar botão "Aplicar Modelo p/ todas as Máquinas", nas maquinas associadas para este modelo - ver item 11. Cadastros

**Comment by PauloImmig** [comment]
Feito!
