### ISSUE TITLE
3. Quando clicar em um quadro "resumo" de uma máquina, interromper chaveamento

### ISSUE THREAD

**Issue by tecsistel** [PauloImmig/MachineMonitoring#13]
Prioridade 3:
3. Quando clicar em um quadro "resumo" de uma máquina, interromper chaveamento de máquinas do foco, ficando fixo na que foi clicada (continua atualizando os dados de todas, mas somente 1 é visível no foco)
 	*Botão play(?) para voltar a chavear.

**Comment by PauloImmig** [comment]
Feito!
