### ISSUE TITLE
5. Quando o foco tem poucos gráficos, os quadrados "resumo" das maquinas "pulam"

### ISSUE THREAD

**Issue by tecsistel** [PauloImmig/MachineMonitoring#15]
Prioridade 5:
5. Quando o foco tem poucos gráficos, os quadrados "resumo" das maquinas "pulam" para o lado esquerdo da tela (abaixo do foco). Ideal é que fiquem sempre na mesma posição, na metade da direita da tela.

**Comment by PauloImmig** [comment]
Na verdade isso foi proposital para usar todo espaço morto da tela. Pretendem que mude mesmo?

**Comment by PauloImmig** [comment]
Feito
