### ISSUE TITLE
2 - Na tela de parametrização, além dos filtros |Modelo| e |Máquina|, adicionar botões 'Aplicar' e 'Aplicar e Zerar' 

### ISSUE THREAD

**Issue by marcelostaub** [PauloImmig/MachineMonitoring#18]
Na tela de parametrização, além dos filtros |Modelo| e |Máquina|, adicionar dois botões:
	2.1- |Aplicar| 		(apenas aplica os parâmetros, sem zerar ciclos);
	2.2- |Aplicar e  Zerar| (aplica os parâmetros e zera_ciclo=1);

**Comment by PauloImmig** [comment]
Filtros de modelo e máquina OK

**Comment by PauloImmig** [comment]
@marcelostaub  Você quer ter um "aplicar" e "aplicar e zerar" na tela de parametrização? Me parece estranho.

**Comment by PauloImmig** [comment]
Feito
